% % Auto-generated by stereoCalibrator app on 07-May-2018
% %-------------------------------------------------------
% 
% 

%% Cleaning
close all hidden;
clear
% % Define images to process
% imageFileNames1 = {'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_0.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_1.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_10.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_11.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_12.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_13.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_14.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_15.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_16.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_17.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_18.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_19.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_2.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_3.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_4.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_5.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_6.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_7.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_8.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\leftCamera\leftImagetTest_9.png',...
%     };
% imageFileNames2 = {'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_0.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_1.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_10.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_11.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_12.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_13.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_14.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_15.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_16.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_17.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_18.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_19.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_2.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_3.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_4.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_5.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_6.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_7.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_8.png',...
%     'C:\Users\akat\Desktop\SteVi\Session 6\rightCamera\rightImageTest_9.png',...
%     };

load('stereoParams.mat') %loads it back in and Matlab recognises it is a structure

stereoParams = stereoParameters(stereoParams) % recreates the stereo parameters object 


load('estimationErrors.mat')
%% Detect checkerboards in images
% [imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames1, imageFileNames2);

%% Generate world coordinates of the checkerboard keypoints
% squareSize = 46;  % in units of 'millimeters'
% worldPoints = generateCheckerboardPoints(boardSize, squareSize);
%  
%% GUI to open file
 
[ workingDir, name, ext] = fileparts( mfilename( 'fullpath'));
ImageDir = [ workingDir, '/Session 7_Beamer/4m/'];
 
[leftFileName,leftPathName] = uigetfile('*.PNG','Select the left image', ImageDir);
if isequal(leftFileName,0)
   disp('User selected Cancel')
else
   disp(['User selected ', fullfile(leftPathName, leftFileName)])
end
 
[rightFileName,rightPathName] = uigetfile('*.PNG','Select the right image', ImageDir);
if isequal(rightFileName,0)
   disp('User selected Cancel')
else
   disp(['User selected ', fullfile(rightPathName, rightFileName)])
end
 
%% Read one of the images from the first stereo pair
I1 = imread(fullfile(leftPathName, leftFileName));
% I1 = imread('LaserTest/leftTest_1.png');
[mrows, ncols, ~] = size(I1);
% 
%% Calibrate the camera
% [stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
%  'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
%      'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
%      'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
%      'ImageSize', [mrows, ncols]);
 
%%% View reprojection errors
% h1=figure; showReprojectionErrors(stereoParams);
 
%%%Visualize pattern locations
% h2=figure; showExtrinsics(stereoParams, 'CameraCentric');
 
%%% Display parameter estimation errors
% displayErrors(estimationErrors, stereoParams2c);
 
% %%Rectify stereo images.
I2 = imread(fullfile(rightPathName, rightFileName));
% I2 = imread('LaserTest/rightTest_1.png');
[J1, J2] = rectifyStereoImages(I1, I2, stereoParams);
figure;
imshow(stereoAnaglyph(J1, J2));
title('Rectified Frames');
frameLeftGray  = rgb2gray(J1);
frameRightGray = rgb2gray(J2);
    
% disparityMap = disparity(J1(:,:,2), J2(:,:,2), 'BlockSize', 5);
disparityMap = disparity(J1(:,:,2), J2(:,:,2), 'BlockSize', 41,...
               'ContrastThreshold', 0.9, 'UniquenessThreshold', 6,...
               'DistanceThreshold', 1,  'TextureThreshold' , 0.00001 );
figure;
imshow(disparityMap, [0, 64]); % durch 16 teilbar
title('Disparity Map');
colormap (gca, 'jet');
colorbar
 

%% Depth map
base = norm(stereoParams.TranslationOfCamera2);
f1x = 3.6*10^(-6) * stereoParams.CameraParameters1.FocalLength(1);
f1y = 3.6*10^(-6) * stereoParams.CameraParameters1.FocalLength(2);

f2x = 3.6*10^(-6) * stereoParams.CameraParameters2.FocalLength(1);
f2y = 3.6*10^(-6) * stereoParams.CameraParameters2.FocalLength(2);

dismin = min( abs(disparityMap(:)) );
f = (f1x + f1y + f2x + f2y)/4 *1000;

depth = base *f ./ (disparityMap*3.6*10^-3) ;
depth = depth ./ 1000;
depthmax = max(depth(:));


figure;
imshow(depth, [0, 8]); % durch 16 teilbar
title('Depth Map');
colormap (gca, 'jet');
colorbar


depth_filtered = medfilt2(depth);
figure;
imshow(depth_filtered , [0, 8]); % durch 16 teilbar
title('Depth Map Filtered');
colormap (gca, 'jet');
colorbar

%% Depth map inpainting
% imI1 = I1(1:size(depth,1) , 1:size(depth,2),:);
% depth(depth < 0) = NaN;
% 
% depthrecover = recover(double(depth), [], imI1);
% figure
% imshow(depthrecover, [0, 32]); % durch 16 teilbar
% title('Depth Map Recover');
% colormap (gca, 'jet');
% colorbar

%% 3D reconstruction
% points3D = reconstructScene(disparityMap, stereoParams);
%  
% %%% Convert to meters and create a pointCloud object
% points3D = points3D ./ 1000;
% ptCloud = pointCloud(points3D, 'Color', J1);
%  
% %%% Create a streaming point cloud viewer
% player3D = pcplayer([-3, 3], [-3, 3], [0, 8], 'VerticalAxis', 'y', ...
%     'VerticalAxisDir', 'down');
%  
% %%% Visualize the point cloud
% view(player3D, ptCloud);
%  
%%% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
% showdemo('DepthEstimationFromStereoVideoExample')
 
%%% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('StereoCalibrationAndSceneReconstructionExample')
% showdemo('DepthEstimationFromStereoVideoExample')

